site_name: Apollo Documentation
site_url: https://docs.apollo.fyi
repo_url: https://github.com/apollo-fyi/apollo-docs
repo_name: apollo-fyi/apollo-docs
edit_uri: edit/main/docs/
site_description: Documentation and guides for the Apollo Discord bot, the best calendar and event bot on Discord.
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.sections
  palette:
    - scheme: default
      primary: light blue
      accent: yellow
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: light blue
      accent: yellow
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: True
nav:
  - Home: 'index.md'
  - Getting started: 'getting_started.md'
  - FAQ: 'faq.md'
  - Commands: 'commands.md'
  - Guides:
    - Creating events: 'creating_events.md'
    - Deleting events: 'deleting_events.md'
    - Modifying events: 'modifying_events.md'
    - Event channels: 'event_channels.md'
    - Reminders: 'reminders.md'
    - Attendee roles: 'attendee_roles.md'
